-- AUTO-GENERATED by scripts/gen_omega_tree5.py from scripts/omega5_tree.json.
-- Regenerate instead of hand-editing.
import EG411Formal.SolutionStructure
import EG411Formal.OmegaTreeSupport

/-!
# EG#411 (r=2): no solution with five distinct prime factors

For `n` satisfying `3·φ(n) = 2n + 2`, there is **no** solution that is a product of
five distinct primes (`omega5_empty`).  This extends the ω-ladder of
`OmegaLadder.lean` (ω = 3 → 1295, ω = 4 → 1679615) one rung higher: at ω = 5 the
ladder terminates with the empty set.

The proof mirrors a machine-enumerated kill-tree (`scripts/omega5_tree.json`,
enumerator `scripts/omega_tree_enumerator.py`).  Writing the equation in product
form `A·∏(pᵢ−1) = B·∏pᵢ + 2` with the already-fixed prefix folded into
`A = 3·∏(p−1)`, `B = 2·∏p`, each tree node is killed by one of:

* **cap** — `B·cʲ + 2 < A·(c−1)ʲ` forces the next prime below `c`
  (`cap_kill_3/4/5`), and the surviving primes in the window are exactly the
  listed branches (a `native_decide` filter computation, using the chain
  conditions `¬ p ∣ (x−1)` from `solution_no_prime_chain`);
* **dead** — `A ≤ B` is outright impossible (`dead_kill_2`);
* **terminal** — two primes `s < t` remain; `t` is pinned to the exact quotient
  `(As−A+2)/((A−B)s−A)` (`terminal_formula`), `s` is bounded by a quadratic
  (`terminal_bound`), and one `native_decide` scan certifies the window is empty.
-/

namespace EG411Structure

set_option linter.style.nativeDecide false

set_option maxHeartbeats 1600000 in
-- 36 case branches with a `ring_nf` constant-fold at every node and 22 terminal
-- `native_decide` scans exceed the default budget.
/-- The equation `3·φ(n) = 2n + 2` has no solution with exactly five distinct
prime factors. -/
theorem omega5_empty {n : ℕ} (hn : 3 * Nat.totient n = 2 * n + 2)
    (p q r s t : ℕ) (hp : p.Prime) (hq : q.Prime) (hr : r.Prime) (hs : s.Prime)
    (ht : t.Prime) (h1 : p < q) (h2 : q < r) (h3 : r < s) (h4 : s < t)
    (hN : n = p * q * r * s * t) : False := by
  have hN' : n = p * (q * (r * (s * t))) := by rw [hN]; ring
  have hd1 : p ∣ n := ⟨q * (r * (s * t)), hN'⟩
  have hd2 : q ∣ n := ⟨p * (r * (s * t)), by rw [hN']; ring⟩
  have hd3 : r ∣ n := ⟨p * (q * (s * t)), by rw [hN']; ring⟩
  have hd4 : s ∣ n := ⟨p * (q * (r * t)), by rw [hN']; ring⟩
  have hp5 : 5 ≤ p := solution_min_prime_ge_five hn p hp hd1
  have hchain := solution_no_prime_chain hn
  have heq0 : 3 * ((p - 1) * ((q - 1) * ((r - 1) * ((s - 1) * (t - 1)))))
      = 2 * (p * (q * (r * (s * t)))) + 2 := by
    have h := hn
    rw [hN', phi_prod_5 hp hq hr hs ht h1 h2 h3 h4] at h
    exact h
  have hcap0 : p < 13 := by
    by_contra hge
    exact cap_kill_5 (c := 13) (by norm_num) (by norm_num) (by omega)
      h1.le h2.le h3.le h4.le heq0
  have hmem0 : p ∈ (Finset.Ioo 4 13).filter
      (fun v => Nat.Prime v) :=
    Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap0⟩, hp⟩
  have hset0 : (Finset.Ioo 4 13).filter
      (fun v => Nat.Prime v)
      = ({5, 7, 11} : Finset ℕ) := by native_decide
  rw [hset0] at hmem0
  fin_cases hmem0
  · -- p = 5
    have heq1 : 12 * ((q - 1) * ((r - 1) * ((s - 1) * (t - 1))))
        = 10 * (q * (r * (s * t))) + 2 := by
      ring_nf at heq0 ⊢
      omega
    have hcap1 : q < 23 := by
      by_contra hge
      exact cap_kill_4 (c := 23) (by norm_num) (by norm_num) (by omega)
        h2.le h3.le h4.le heq1
    have hch1_5 : ¬ (5:ℕ) ∣ (q - 1) :=
      hchain 5 q (by norm_num) hq hd1 hd2
    have hmem1 : q ∈ (Finset.Ioo 5 23).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap1⟩, hq, hch1_5⟩
    have hset1 : (Finset.Ioo 5 23).filter
        (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1))
        = ({7, 13, 17, 19} : Finset ℕ) := by native_decide
    rw [hset1] at hmem1
    fin_cases hmem1
    · -- q = 7
      have heq2 : 72 * ((r - 1) * ((s - 1) * (t - 1)))
          = 70 * (r * (s * t)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : r < 107 := by
        by_contra hge
        exact cap_kill_3 (c := 107) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_5 : ¬ (5:ℕ) ∣ (r - 1) :=
        hchain 5 r (by norm_num) hr hd1 hd3
      have hch2_7 : ¬ (7:ℕ) ∣ (r - 1) :=
        hchain 7 r (by norm_num) hr hd2 hd3
      have hmem2 : r ∈ (Finset.Ioo 7 107).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 7 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hr, hch2_5, hch2_7⟩
      have hset2 : (Finset.Ioo 7 107).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 7 ∣ (v - 1))
          = ({13, 17, 19, 23, 37, 47, 53, 59,
              67, 73, 79, 83, 89, 97, 103} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- r = 13
        have heq3 : 864 * ((s - 1) * (t - 1))
            = 910 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        exact dead_kill_2 (by norm_num) heq3
      · -- r = 17
        have heq3 : 1152 * ((s - 1) * (t - 1))
            = 1190 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        exact dead_kill_2 (by norm_num) heq3
      · -- r = 19
        have heq3 : 1296 * ((s - 1) * (t - 1))
            = 1330 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        exact dead_kill_2 (by norm_num) heq3
      · -- r = 23
        have heq3 : 1584 * ((s - 1) * (t - 1))
            = 1610 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        exact dead_kill_2 (by norm_num) heq3
      · -- r = 37
        have heq3 : 2592 * ((s - 1) * (t - 1))
            = 2590 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 2593 := by nlinarith [hbnd]
        by_cases hden : 2592 < (2592 - 2590) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (s - 1) :=
            hchain 7 s (by norm_num) hs hd2 hd4
          have hch3_37 : ¬ (37:ℕ) ∣ (s - 1) :=
            hchain 37 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 37 2593).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((2592 - 2590) * v - 2592) ∣ (2592 * v - 2592 + 2) ∧
                Nat.Prime ((2592 * v - 2592 + 2) / ((2592 - 2590) * v - 2592)) ∧
                v < (2592 * v - 2592 + 2) / ((2592 - 2590) * v - 2592)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_7, hch3_37, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 37 2593).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 37 ∣ (v - 1) ∧
                ((2592 - 2590) * v - 2592) ∣ (2592 * v - 2592 + 2) ∧
                Nat.Prime ((2592 * v - 2592 + 2) / ((2592 - 2590) * v - 2592)) ∧
                v < (2592 * v - 2592 + 2) / ((2592 - 2590) * v - 2592))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 47
        have heq3 : 3312 * ((s - 1) * (t - 1))
            = 3290 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 302 := by nlinarith [hbnd]
        by_cases hden : 3312 < (3312 - 3290) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (s - 1) :=
            hchain 7 s (by norm_num) hs hd2 hd4
          have hch3_47 : ¬ (47:ℕ) ∣ (s - 1) :=
            hchain 47 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 47 302).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 47 ∣ (v - 1) ∧
                ((3312 - 3290) * v - 3312) ∣ (3312 * v - 3312 + 2) ∧
                Nat.Prime ((3312 * v - 3312 + 2) / ((3312 - 3290) * v - 3312)) ∧
                v < (3312 * v - 3312 + 2) / ((3312 - 3290) * v - 3312)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_7, hch3_47, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 47 302).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 47 ∣ (v - 1) ∧
                ((3312 - 3290) * v - 3312) ∣ (3312 * v - 3312 + 2) ∧
                Nat.Prime ((3312 * v - 3312 + 2) / ((3312 - 3290) * v - 3312)) ∧
                v < (3312 * v - 3312 + 2) / ((3312 - 3290) * v - 3312))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 53
        have heq3 : 3744 * ((s - 1) * (t - 1))
            = 3710 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 221 := by nlinarith [hbnd]
        by_cases hden : 3744 < (3744 - 3710) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (s - 1) :=
            hchain 7 s (by norm_num) hs hd2 hd4
          have hch3_53 : ¬ (53:ℕ) ∣ (s - 1) :=
            hchain 53 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 53 221).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 53 ∣ (v - 1) ∧
                ((3744 - 3710) * v - 3744) ∣ (3744 * v - 3744 + 2) ∧
                Nat.Prime ((3744 * v - 3744 + 2) / ((3744 - 3710) * v - 3744)) ∧
                v < (3744 * v - 3744 + 2) / ((3744 - 3710) * v - 3744)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_7, hch3_53, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 53 221).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 53 ∣ (v - 1) ∧
                ((3744 - 3710) * v - 3744) ∣ (3744 * v - 3744 + 2) ∧
                Nat.Prime ((3744 * v - 3744 + 2) / ((3744 - 3710) * v - 3744)) ∧
                v < (3744 * v - 3744 + 2) / ((3744 - 3710) * v - 3744))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 59
        have heq3 : 4176 * ((s - 1) * (t - 1))
            = 4130 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 183 := by nlinarith [hbnd]
        by_cases hden : 4176 < (4176 - 4130) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (s - 1) :=
            hchain 7 s (by norm_num) hs hd2 hd4
          have hch3_59 : ¬ (59:ℕ) ∣ (s - 1) :=
            hchain 59 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 59 183).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 59 ∣ (v - 1) ∧
                ((4176 - 4130) * v - 4176) ∣ (4176 * v - 4176 + 2) ∧
                Nat.Prime ((4176 * v - 4176 + 2) / ((4176 - 4130) * v - 4176)) ∧
                v < (4176 * v - 4176 + 2) / ((4176 - 4130) * v - 4176)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_7, hch3_59, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 59 183).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 59 ∣ (v - 1) ∧
                ((4176 - 4130) * v - 4176) ∣ (4176 * v - 4176 + 2) ∧
                Nat.Prime ((4176 * v - 4176 + 2) / ((4176 - 4130) * v - 4176)) ∧
                v < (4176 * v - 4176 + 2) / ((4176 - 4130) * v - 4176))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 67
        have heq3 : 4752 * ((s - 1) * (t - 1))
            = 4690 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 154 := by nlinarith [hbnd]
        by_cases hden : 4752 < (4752 - 4690) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (s - 1) :=
            hchain 7 s (by norm_num) hs hd2 hd4
          have hch3_67 : ¬ (67:ℕ) ∣ (s - 1) :=
            hchain 67 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 67 154).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 67 ∣ (v - 1) ∧
                ((4752 - 4690) * v - 4752) ∣ (4752 * v - 4752 + 2) ∧
                Nat.Prime ((4752 * v - 4752 + 2) / ((4752 - 4690) * v - 4752)) ∧
                v < (4752 * v - 4752 + 2) / ((4752 - 4690) * v - 4752)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_7, hch3_67, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 67 154).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 67 ∣ (v - 1) ∧
                ((4752 - 4690) * v - 4752) ∣ (4752 * v - 4752 + 2) ∧
                Nat.Prime ((4752 * v - 4752 + 2) / ((4752 - 4690) * v - 4752)) ∧
                v < (4752 * v - 4752 + 2) / ((4752 - 4690) * v - 4752))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 73
        have heq3 : 5184 * ((s - 1) * (t - 1))
            = 5110 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 141 := by nlinarith [hbnd]
        by_cases hden : 5184 < (5184 - 5110) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (s - 1) :=
            hchain 7 s (by norm_num) hs hd2 hd4
          have hch3_73 : ¬ (73:ℕ) ∣ (s - 1) :=
            hchain 73 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 73 141).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 73 ∣ (v - 1) ∧
                ((5184 - 5110) * v - 5184) ∣ (5184 * v - 5184 + 2) ∧
                Nat.Prime ((5184 * v - 5184 + 2) / ((5184 - 5110) * v - 5184)) ∧
                v < (5184 * v - 5184 + 2) / ((5184 - 5110) * v - 5184)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_7, hch3_73, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 73 141).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 73 ∣ (v - 1) ∧
                ((5184 - 5110) * v - 5184) ∣ (5184 * v - 5184 + 2) ∧
                Nat.Prime ((5184 * v - 5184 + 2) / ((5184 - 5110) * v - 5184)) ∧
                v < (5184 * v - 5184 + 2) / ((5184 - 5110) * v - 5184))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 79
        have heq3 : 5616 * ((s - 1) * (t - 1))
            = 5530 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 132 := by nlinarith [hbnd]
        by_cases hden : 5616 < (5616 - 5530) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (s - 1) :=
            hchain 7 s (by norm_num) hs hd2 hd4
          have hch3_79 : ¬ (79:ℕ) ∣ (s - 1) :=
            hchain 79 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 79 132).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 79 ∣ (v - 1) ∧
                ((5616 - 5530) * v - 5616) ∣ (5616 * v - 5616 + 2) ∧
                Nat.Prime ((5616 * v - 5616 + 2) / ((5616 - 5530) * v - 5616)) ∧
                v < (5616 * v - 5616 + 2) / ((5616 - 5530) * v - 5616)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_7, hch3_79, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 79 132).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 79 ∣ (v - 1) ∧
                ((5616 - 5530) * v - 5616) ∣ (5616 * v - 5616 + 2) ∧
                Nat.Prime ((5616 * v - 5616 + 2) / ((5616 - 5530) * v - 5616)) ∧
                v < (5616 * v - 5616 + 2) / ((5616 - 5530) * v - 5616))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 83
        have heq3 : 5904 * ((s - 1) * (t - 1))
            = 5810 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 127 := by nlinarith [hbnd]
        by_cases hden : 5904 < (5904 - 5810) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (s - 1) :=
            hchain 7 s (by norm_num) hs hd2 hd4
          have hch3_83 : ¬ (83:ℕ) ∣ (s - 1) :=
            hchain 83 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 83 127).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 83 ∣ (v - 1) ∧
                ((5904 - 5810) * v - 5904) ∣ (5904 * v - 5904 + 2) ∧
                Nat.Prime ((5904 * v - 5904 + 2) / ((5904 - 5810) * v - 5904)) ∧
                v < (5904 * v - 5904 + 2) / ((5904 - 5810) * v - 5904)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_7, hch3_83, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 83 127).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 83 ∣ (v - 1) ∧
                ((5904 - 5810) * v - 5904) ∣ (5904 * v - 5904 + 2) ∧
                Nat.Prime ((5904 * v - 5904 + 2) / ((5904 - 5810) * v - 5904)) ∧
                v < (5904 * v - 5904 + 2) / ((5904 - 5810) * v - 5904))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 89
        have heq3 : 6336 * ((s - 1) * (t - 1))
            = 6230 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 121 := by nlinarith [hbnd]
        by_cases hden : 6336 < (6336 - 6230) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (s - 1) :=
            hchain 7 s (by norm_num) hs hd2 hd4
          have hch3_89 : ¬ (89:ℕ) ∣ (s - 1) :=
            hchain 89 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 89 121).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 89 ∣ (v - 1) ∧
                ((6336 - 6230) * v - 6336) ∣ (6336 * v - 6336 + 2) ∧
                Nat.Prime ((6336 * v - 6336 + 2) / ((6336 - 6230) * v - 6336)) ∧
                v < (6336 * v - 6336 + 2) / ((6336 - 6230) * v - 6336)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_7, hch3_89, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 89 121).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 89 ∣ (v - 1) ∧
                ((6336 - 6230) * v - 6336) ∣ (6336 * v - 6336 + 2) ∧
                Nat.Prime ((6336 * v - 6336 + 2) / ((6336 - 6230) * v - 6336)) ∧
                v < (6336 * v - 6336 + 2) / ((6336 - 6230) * v - 6336))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 97
        have heq3 : 6912 * ((s - 1) * (t - 1))
            = 6790 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 114 := by nlinarith [hbnd]
        by_cases hden : 6912 < (6912 - 6790) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (s - 1) :=
            hchain 7 s (by norm_num) hs hd2 hd4
          have hch3_97 : ¬ (97:ℕ) ∣ (s - 1) :=
            hchain 97 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 97 114).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 97 ∣ (v - 1) ∧
                ((6912 - 6790) * v - 6912) ∣ (6912 * v - 6912 + 2) ∧
                Nat.Prime ((6912 * v - 6912 + 2) / ((6912 - 6790) * v - 6912)) ∧
                v < (6912 * v - 6912 + 2) / ((6912 - 6790) * v - 6912)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_7, hch3_97, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 97 114).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 97 ∣ (v - 1) ∧
                ((6912 - 6790) * v - 6912) ∣ (6912 * v - 6912 + 2) ∧
                Nat.Prime ((6912 * v - 6912 + 2) / ((6912 - 6790) * v - 6912)) ∧
                v < (6912 * v - 6912 + 2) / ((6912 - 6790) * v - 6912))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 103
        have heq3 : 7344 * ((s - 1) * (t - 1))
            = 7210 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 111 := by nlinarith [hbnd]
        by_cases hden : 7344 < (7344 - 7210) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_7 : ¬ (7:ℕ) ∣ (s - 1) :=
            hchain 7 s (by norm_num) hs hd2 hd4
          have hch3_103 : ¬ (103:ℕ) ∣ (s - 1) :=
            hchain 103 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 103 111).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 103 ∣ (v - 1) ∧
                ((7344 - 7210) * v - 7344) ∣ (7344 * v - 7344 + 2) ∧
                Nat.Prime ((7344 * v - 7344 + 2) / ((7344 - 7210) * v - 7344)) ∧
                v < (7344 * v - 7344 + 2) / ((7344 - 7210) * v - 7344)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_7, hch3_103, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 103 111).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 103 ∣ (v - 1) ∧
                ((7344 - 7210) * v - 7344) ∣ (7344 * v - 7344 + 2) ∧
                Nat.Prime ((7344 * v - 7344 + 2) / ((7344 - 7210) * v - 7344)) ∧
                v < (7344 * v - 7344 + 2) / ((7344 - 7210) * v - 7344))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
    · -- q = 13
      have heq2 : 144 * ((r - 1) * ((s - 1) * (t - 1)))
          = 130 * (r * (s * t)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : r < 31 := by
        by_contra hge
        exact cap_kill_3 (c := 31) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_5 : ¬ (5:ℕ) ∣ (r - 1) :=
        hchain 5 r (by norm_num) hr hd1 hd3
      have hch2_13 : ¬ (13:ℕ) ∣ (r - 1) :=
        hchain 13 r (by norm_num) hr hd2 hd3
      have hmem2 : r ∈ (Finset.Ioo 13 31).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hr, hch2_5, hch2_13⟩
      have hset2 : (Finset.Ioo 13 31).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1))
          = ({17, 19, 23, 29} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- r = 17
        have heq3 : 2304 * ((s - 1) * (t - 1))
            = 2210 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 50 := by nlinarith [hbnd]
        by_cases hden : 2304 < (2304 - 2210) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_13 : ¬ (13:ℕ) ∣ (s - 1) :=
            hchain 13 s (by norm_num) hs hd2 hd4
          have hch3_17 : ¬ (17:ℕ) ∣ (s - 1) :=
            hchain 17 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 17 50).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((2304 - 2210) * v - 2304) ∣ (2304 * v - 2304 + 2) ∧
                Nat.Prime ((2304 * v - 2304 + 2) / ((2304 - 2210) * v - 2304)) ∧
                v < (2304 * v - 2304 + 2) / ((2304 - 2210) * v - 2304)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_13, hch3_17, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 17 50).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((2304 - 2210) * v - 2304) ∣ (2304 * v - 2304 + 2) ∧
                Nat.Prime ((2304 * v - 2304 + 2) / ((2304 - 2210) * v - 2304)) ∧
                v < (2304 * v - 2304 + 2) / ((2304 - 2210) * v - 2304))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 19
        have heq3 : 2592 * ((s - 1) * (t - 1))
            = 2470 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 43 := by nlinarith [hbnd]
        by_cases hden : 2592 < (2592 - 2470) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_13 : ¬ (13:ℕ) ∣ (s - 1) :=
            hchain 13 s (by norm_num) hs hd2 hd4
          have hch3_19 : ¬ (19:ℕ) ∣ (s - 1) :=
            hchain 19 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 19 43).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ((2592 - 2470) * v - 2592) ∣ (2592 * v - 2592 + 2) ∧
                Nat.Prime ((2592 * v - 2592 + 2) / ((2592 - 2470) * v - 2592)) ∧
                v < (2592 * v - 2592 + 2) / ((2592 - 2470) * v - 2592)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_13, hch3_19, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 19 43).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ((2592 - 2470) * v - 2592) ∣ (2592 * v - 2592 + 2) ∧
                Nat.Prime ((2592 * v - 2592 + 2) / ((2592 - 2470) * v - 2592)) ∧
                v < (2592 * v - 2592 + 2) / ((2592 - 2470) * v - 2592))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 23
        have heq3 : 3168 * ((s - 1) * (t - 1))
            = 2990 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 37 := by nlinarith [hbnd]
        by_cases hden : 3168 < (3168 - 2990) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_13 : ¬ (13:ℕ) ∣ (s - 1) :=
            hchain 13 s (by norm_num) hs hd2 hd4
          have hch3_23 : ¬ (23:ℕ) ∣ (s - 1) :=
            hchain 23 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 23 37).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((3168 - 2990) * v - 3168) ∣ (3168 * v - 3168 + 2) ∧
                Nat.Prime ((3168 * v - 3168 + 2) / ((3168 - 2990) * v - 3168)) ∧
                v < (3168 * v - 3168 + 2) / ((3168 - 2990) * v - 3168)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_13, hch3_23, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 23 37).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((3168 - 2990) * v - 3168) ∣ (3168 * v - 3168 + 2) ∧
                Nat.Prime ((3168 * v - 3168 + 2) / ((3168 - 2990) * v - 3168)) ∧
                v < (3168 * v - 3168 + 2) / ((3168 - 2990) * v - 3168))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 29
        have heq3 : 4032 * ((s - 1) * (t - 1))
            = 3770 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 32 := by nlinarith [hbnd]
        by_cases hden : 4032 < (4032 - 3770) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_13 : ¬ (13:ℕ) ∣ (s - 1) :=
            hchain 13 s (by norm_num) hs hd2 hd4
          have hch3_29 : ¬ (29:ℕ) ∣ (s - 1) :=
            hchain 29 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 29 32).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((4032 - 3770) * v - 4032) ∣ (4032 * v - 4032 + 2) ∧
                Nat.Prime ((4032 * v - 4032 + 2) / ((4032 - 3770) * v - 4032)) ∧
                v < (4032 * v - 4032 + 2) / ((4032 - 3770) * v - 4032)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_13, hch3_29, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 29 32).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 29 ∣ (v - 1) ∧
                ((4032 - 3770) * v - 4032) ∣ (4032 * v - 4032 + 2) ∧
                Nat.Prime ((4032 * v - 4032 + 2) / ((4032 - 3770) * v - 4032)) ∧
                v < (4032 * v - 4032 + 2) / ((4032 - 3770) * v - 4032))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
    · -- q = 17
      have heq2 : 192 * ((r - 1) * ((s - 1) * (t - 1)))
          = 170 * (r * (s * t)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : r < 29 := by
        by_contra hge
        exact cap_kill_3 (c := 29) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_5 : ¬ (5:ℕ) ∣ (r - 1) :=
        hchain 5 r (by norm_num) hr hd1 hd3
      have hch2_17 : ¬ (17:ℕ) ∣ (r - 1) :=
        hchain 17 r (by norm_num) hr hd2 hd3
      have hmem2 : r ∈ (Finset.Ioo 17 29).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hr, hch2_5, hch2_17⟩
      have hset2 : (Finset.Ioo 17 29).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 17 ∣ (v - 1))
          = ({19, 23} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- r = 19
        have heq3 : 3456 * ((s - 1) * (t - 1))
            = 3230 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 32 := by nlinarith [hbnd]
        by_cases hden : 3456 < (3456 - 3230) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_17 : ¬ (17:ℕ) ∣ (s - 1) :=
            hchain 17 s (by norm_num) hs hd2 hd4
          have hch3_19 : ¬ (19:ℕ) ∣ (s - 1) :=
            hchain 19 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 19 32).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ((3456 - 3230) * v - 3456) ∣ (3456 * v - 3456 + 2) ∧
                Nat.Prime ((3456 * v - 3456 + 2) / ((3456 - 3230) * v - 3456)) ∧
                v < (3456 * v - 3456 + 2) / ((3456 - 3230) * v - 3456)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_17, hch3_19, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 19 32).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ((3456 - 3230) * v - 3456) ∣ (3456 * v - 3456 + 2) ∧
                Nat.Prime ((3456 * v - 3456 + 2) / ((3456 - 3230) * v - 3456)) ∧
                v < (3456 * v - 3456 + 2) / ((3456 - 3230) * v - 3456))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 23
        have heq3 : 4224 * ((s - 1) * (t - 1))
            = 3910 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 28 := by nlinarith [hbnd]
        by_cases hden : 4224 < (4224 - 3910) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_17 : ¬ (17:ℕ) ∣ (s - 1) :=
            hchain 17 s (by norm_num) hs hd2 hd4
          have hch3_23 : ¬ (23:ℕ) ∣ (s - 1) :=
            hchain 23 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 23 28).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((4224 - 3910) * v - 4224) ∣ (4224 * v - 4224 + 2) ∧
                Nat.Prime ((4224 * v - 4224 + 2) / ((4224 - 3910) * v - 4224)) ∧
                v < (4224 * v - 4224 + 2) / ((4224 - 3910) * v - 4224)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_17, hch3_23, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 23 28).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((4224 - 3910) * v - 4224) ∣ (4224 * v - 4224 + 2) ∧
                Nat.Prime ((4224 * v - 4224 + 2) / ((4224 - 3910) * v - 4224)) ∧
                v < (4224 * v - 4224 + 2) / ((4224 - 3910) * v - 4224))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
    · -- q = 19
      have heq2 : 216 * ((r - 1) * ((s - 1) * (t - 1)))
          = 190 * (r * (s * t)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : r < 29 := by
        by_contra hge
        exact cap_kill_3 (c := 29) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_5 : ¬ (5:ℕ) ∣ (r - 1) :=
        hchain 5 r (by norm_num) hr hd1 hd3
      have hch2_19 : ¬ (19:ℕ) ∣ (r - 1) :=
        hchain 19 r (by norm_num) hr hd2 hd3
      have hmem2 : r ∈ (Finset.Ioo 19 29).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hr, hch2_5, hch2_19⟩
      have hset2 : (Finset.Ioo 19 29).filter
          (fun v => Nat.Prime v ∧ ¬ 5 ∣ (v - 1) ∧ ¬ 19 ∣ (v - 1))
          = ({23} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- r = 23
        have heq3 : 4752 * ((s - 1) * (t - 1))
            = 4370 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 26 := by nlinarith [hbnd]
        by_cases hden : 4752 < (4752 - 4370) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_5 : ¬ (5:ℕ) ∣ (s - 1) :=
            hchain 5 s (by norm_num) hs hd1 hd4
          have hch3_19 : ¬ (19:ℕ) ∣ (s - 1) :=
            hchain 19 s (by norm_num) hs hd2 hd4
          have hch3_23 : ¬ (23:ℕ) ∣ (s - 1) :=
            hchain 23 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 23 26).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((4752 - 4370) * v - 4752) ∣ (4752 * v - 4752 + 2) ∧
                Nat.Prime ((4752 * v - 4752 + 2) / ((4752 - 4370) * v - 4752)) ∧
                v < (4752 * v - 4752 + 2) / ((4752 - 4370) * v - 4752)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_5, hch3_19, hch3_23, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 23 26).filter (fun v =>
                Nat.Prime v ∧
                ¬ 5 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ¬ 23 ∣ (v - 1) ∧
                ((4752 - 4370) * v - 4752) ∣ (4752 * v - 4752 + 2) ∧
                Nat.Prime ((4752 * v - 4752 + 2) / ((4752 - 4370) * v - 4752)) ∧
                v < (4752 * v - 4752 + 2) / ((4752 - 4370) * v - 4752))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
  · -- p = 7
    have heq1 : 18 * ((q - 1) * ((r - 1) * ((s - 1) * (t - 1))))
        = 14 * (q * (r * (s * t))) + 2 := by
      ring_nf at heq0 ⊢
      omega
    have hcap1 : q < 17 := by
      by_contra hge
      exact cap_kill_4 (c := 17) (by norm_num) (by norm_num) (by omega)
        h2.le h3.le h4.le heq1
    have hch1_7 : ¬ (7:ℕ) ∣ (q - 1) :=
      hchain 7 q (by norm_num) hq hd1 hd2
    have hmem1 : q ∈ (Finset.Ioo 7 17).filter
        (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap1⟩, hq, hch1_7⟩
    have hset1 : (Finset.Ioo 7 17).filter
        (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1))
        = ({11, 13} : Finset ℕ) := by native_decide
    rw [hset1] at hmem1
    fin_cases hmem1
    · -- q = 11
      have heq2 : 180 * ((r - 1) * ((s - 1) * (t - 1)))
          = 154 * (r * (s * t)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : r < 23 := by
        by_contra hge
        exact cap_kill_3 (c := 23) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_7 : ¬ (7:ℕ) ∣ (r - 1) :=
        hchain 7 r (by norm_num) hr hd1 hd3
      have hch2_11 : ¬ (11:ℕ) ∣ (r - 1) :=
        hchain 11 r (by norm_num) hr hd2 hd3
      have hmem2 : r ∈ (Finset.Ioo 11 23).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 11 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hr, hch2_7, hch2_11⟩
      have hset2 : (Finset.Ioo 11 23).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 11 ∣ (v - 1))
          = ({13, 17, 19} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- r = 13
        have heq3 : 2160 * ((s - 1) * (t - 1))
            = 2002 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 28 := by nlinarith [hbnd]
        by_cases hden : 2160 < (2160 - 2002) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_7 : ¬ (7:ℕ) ∣ (s - 1) :=
            hchain 7 s (by norm_num) hs hd1 hd4
          have hch3_11 : ¬ (11:ℕ) ∣ (s - 1) :=
            hchain 11 s (by norm_num) hs hd2 hd4
          have hch3_13 : ¬ (13:ℕ) ∣ (s - 1) :=
            hchain 13 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 13 28).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ((2160 - 2002) * v - 2160) ∣ (2160 * v - 2160 + 2) ∧
                Nat.Prime ((2160 * v - 2160 + 2) / ((2160 - 2002) * v - 2160)) ∧
                v < (2160 * v - 2160 + 2) / ((2160 - 2002) * v - 2160)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_7, hch3_11, hch3_13, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 13 28).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ((2160 - 2002) * v - 2160) ∣ (2160 * v - 2160 + 2) ∧
                Nat.Prime ((2160 * v - 2160 + 2) / ((2160 - 2002) * v - 2160)) ∧
                v < (2160 * v - 2160 + 2) / ((2160 - 2002) * v - 2160))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 17
        have heq3 : 2880 * ((s - 1) * (t - 1))
            = 2618 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 23 := by nlinarith [hbnd]
        by_cases hden : 2880 < (2880 - 2618) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_7 : ¬ (7:ℕ) ∣ (s - 1) :=
            hchain 7 s (by norm_num) hs hd1 hd4
          have hch3_11 : ¬ (11:ℕ) ∣ (s - 1) :=
            hchain 11 s (by norm_num) hs hd2 hd4
          have hch3_17 : ¬ (17:ℕ) ∣ (s - 1) :=
            hchain 17 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 17 23).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((2880 - 2618) * v - 2880) ∣ (2880 * v - 2880 + 2) ∧
                Nat.Prime ((2880 * v - 2880 + 2) / ((2880 - 2618) * v - 2880)) ∧
                v < (2880 * v - 2880 + 2) / ((2880 - 2618) * v - 2880)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_7, hch3_11, hch3_17, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 17 23).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((2880 - 2618) * v - 2880) ∣ (2880 * v - 2880 + 2) ∧
                Nat.Prime ((2880 * v - 2880 + 2) / ((2880 - 2618) * v - 2880)) ∧
                v < (2880 * v - 2880 + 2) / ((2880 - 2618) * v - 2880))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
      · -- r = 19
        have heq3 : 3240 * ((s - 1) * (t - 1))
            = 2926 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 22 := by nlinarith [hbnd]
        by_cases hden : 3240 < (3240 - 2926) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_7 : ¬ (7:ℕ) ∣ (s - 1) :=
            hchain 7 s (by norm_num) hs hd1 hd4
          have hch3_11 : ¬ (11:ℕ) ∣ (s - 1) :=
            hchain 11 s (by norm_num) hs hd2 hd4
          have hch3_19 : ¬ (19:ℕ) ∣ (s - 1) :=
            hchain 19 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 19 22).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ((3240 - 2926) * v - 3240) ∣ (3240 * v - 3240 + 2) ∧
                Nat.Prime ((3240 * v - 3240 + 2) / ((3240 - 2926) * v - 3240)) ∧
                v < (3240 * v - 3240 + 2) / ((3240 - 2926) * v - 3240)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_7, hch3_11, hch3_19, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 19 22).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 11 ∣ (v - 1) ∧
                ¬ 19 ∣ (v - 1) ∧
                ((3240 - 2926) * v - 3240) ∣ (3240 * v - 3240 + 2) ∧
                Nat.Prime ((3240 * v - 3240 + 2) / ((3240 - 2926) * v - 3240)) ∧
                v < (3240 * v - 3240 + 2) / ((3240 - 2926) * v - 3240))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
    · -- q = 13
      have heq2 : 216 * ((r - 1) * ((s - 1) * (t - 1)))
          = 182 * (r * (s * t)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : r < 19 := by
        by_contra hge
        exact cap_kill_3 (c := 19) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_7 : ¬ (7:ℕ) ∣ (r - 1) :=
        hchain 7 r (by norm_num) hr hd1 hd3
      have hch2_13 : ¬ (13:ℕ) ∣ (r - 1) :=
        hchain 13 r (by norm_num) hr hd2 hd3
      have hmem2 : r ∈ (Finset.Ioo 13 19).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hr, hch2_7, hch2_13⟩
      have hset2 : (Finset.Ioo 13 19).filter
          (fun v => Nat.Prime v ∧ ¬ 7 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1))
          = ({17} : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      fin_cases hmem2
      · -- r = 17
        have heq3 : 3456 * ((s - 1) * (t - 1))
            = 3094 * (s * t) + 2 := by
          ring_nf at heq2 ⊢
          omega
        have hs2 : 2 ≤ s := by omega
        have hbnd := terminal_bound (by norm_num) heq3 h4 hs2
        have hshi : s ≤ 20 := by nlinarith [hbnd]
        by_cases hden : 3456 < (3456 - 3094) * s
        · obtain ⟨hdvd, htval⟩ := terminal_formula (by norm_num) heq3 h4 hs2 hden
          have hch3_7 : ¬ (7:ℕ) ∣ (s - 1) :=
            hchain 7 s (by norm_num) hs hd1 hd4
          have hch3_13 : ¬ (13:ℕ) ∣ (s - 1) :=
            hchain 13 s (by norm_num) hs hd2 hd4
          have hch3_17 : ¬ (17:ℕ) ∣ (s - 1) :=
            hchain 17 s (by norm_num) hs hd3 hd4
          have hmem3 : s ∈ (Finset.Ioc 17 20).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((3456 - 3094) * v - 3456) ∣ (3456 * v - 3456 + 2) ∧
                Nat.Prime ((3456 * v - 3456 + 2) / ((3456 - 3094) * v - 3456)) ∧
                v < (3456 * v - 3456 + 2) / ((3456 - 3094) * v - 3456)) :=
            Finset.mem_filter.mpr ⟨Finset.mem_Ioc.mpr ⟨by omega, hshi⟩,
              hs, hch3_7, hch3_13, hch3_17, hdvd,
              by rw [htval]; exact ht, by rw [htval]; exact h4⟩
          have hempty : (Finset.Ioc 17 20).filter (fun v =>
                Nat.Prime v ∧
                ¬ 7 ∣ (v - 1) ∧
                ¬ 13 ∣ (v - 1) ∧
                ¬ 17 ∣ (v - 1) ∧
                ((3456 - 3094) * v - 3456) ∣ (3456 * v - 3456 + 2) ∧
                Nat.Prime ((3456 * v - 3456 + 2) / ((3456 - 3094) * v - 3456)) ∧
                v < (3456 * v - 3456 + 2) / ((3456 - 3094) * v - 3456))
              = ∅ := by native_decide
          rw [hempty] at hmem3
          simp at hmem3
        · exact terminal_low_kill (by norm_num) heq3 h4 hs2 (by omega)
  · -- p = 11
    have heq1 : 30 * ((q - 1) * ((r - 1) * ((s - 1) * (t - 1))))
        = 22 * (q * (r * (s * t))) + 2 := by
      ring_nf at heq0 ⊢
      omega
    have hcap1 : q < 17 := by
      by_contra hge
      exact cap_kill_4 (c := 17) (by norm_num) (by norm_num) (by omega)
        h2.le h3.le h4.le heq1
    have hch1_11 : ¬ (11:ℕ) ∣ (q - 1) :=
      hchain 11 q (by norm_num) hq hd1 hd2
    have hmem1 : q ∈ (Finset.Ioo 11 17).filter
        (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap1⟩, hq, hch1_11⟩
    have hset1 : (Finset.Ioo 11 17).filter
        (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1))
        = ({13} : Finset ℕ) := by native_decide
    rw [hset1] at hmem1
    fin_cases hmem1
    · -- q = 13
      have heq2 : 360 * ((r - 1) * ((s - 1) * (t - 1)))
          = 286 * (r * (s * t)) + 2 := by
        ring_nf at heq1 ⊢
        omega
      have hcap2 : r < 17 := by
        by_contra hge
        exact cap_kill_3 (c := 17) (by norm_num) (by norm_num) (by omega)
          h3.le h4.le heq2
      have hch2_11 : ¬ (11:ℕ) ∣ (r - 1) :=
        hchain 11 r (by norm_num) hr hd1 hd3
      have hch2_13 : ¬ (13:ℕ) ∣ (r - 1) :=
        hchain 13 r (by norm_num) hr hd2 hd3
      have hmem2 : r ∈ (Finset.Ioo 13 17).filter
          (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1)) :=
        Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr ⟨by omega, hcap2⟩, hr, hch2_11, hch2_13⟩
      have hset2 : (Finset.Ioo 13 17).filter
          (fun v => Nat.Prime v ∧ ¬ 11 ∣ (v - 1) ∧ ¬ 13 ∣ (v - 1))
          = (∅ : Finset ℕ) := by native_decide
      rw [hset2] at hmem2
      simp at hmem2

end EG411Structure
